/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzevideogatewayApplet;

import static fuzevideogatewayApplet.MainGUI.sele;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GS-1062
 */
public class AddLogFile extends javax.swing.JFrame {

    /**
     * Creates new form AddLogFile
     */
    public AddLogFile() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("fuzelog.png")));
        String path = System.getProperty("user.name");
        File f = new File(path+"fuze.odb");

        try{
            Connection conn=DriverManager.getConnection("jdbc:ucanaccess://"+f);
            Statement s = null;
            s = conn.createStatement();
            ResultSet rs;

            rs = s.executeQuery("select GROUP_NAME from GROUPS;");
    
            while (rs.next()) {
     
                combo_grp.addItem(rs.getString("GROUP_NAME").toString());
            }
        }
        catch(Exception e){
            System.out.printf("\n\t Exception in table "+e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_logfile = new javax.swing.JTextField();
        txt_path = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        combo_grp = new javax.swing.JComboBox();
        combo_ser = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jLabel1.setText("Server :");

        jLabel2.setText("File :");

        jLabel3.setText("Path : ");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Group :");

        combo_grp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                combo_grpFocusLost(evt);
            }
        });
        combo_grp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_grpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(combo_grp, javax.swing.GroupLayout.Alignment.LEADING, 0, 283, Short.MAX_VALUE)
                    .addComponent(combo_ser, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_path, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_logfile))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo_grp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_ser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_logfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combo_grp, combo_ser, txt_logfile, txt_path});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_grpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_grpActionPerformed

    

    }//GEN-LAST:event_combo_grpActionPerformed

    private void combo_grpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_grpFocusLost

        String path = System.getProperty("user.name");
        File f = new File(path+"fuze.odb");
        String sele = combo_grp.getSelectedItem().toString();
        combo_ser.removeAllItems();
    
        try{
            Connection conn=DriverManager.getConnection("jdbc:ucanaccess://"+f);
            Statement s = null;
            s = conn.createStatement();
            ResultSet rs;

            rs = s.executeQuery("select SERVER_NAME from SERVERS where GROUPID =(select GID from GROUPS WHERE GROUP_NAME=\""+sele+"\");");
            while (rs.next()) {
      
                combo_ser.addItem(rs.getString("SERVER_NAME").toString());
            }
        }
        catch(Exception e){
            System.out.printf("\n\t Exception in table "+e);
        }
    }//GEN-LAST:event_combo_grpFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String path = System.getProperty("user.name");
        File f = new File(path+"fuze.odb");
        try{
                Connection conn=DriverManager.getConnection("jdbc:ucanaccess://"+f);
                Statement s = null;
                s = conn.createStatement();
     
                ResultSet rs;
                rs = s.executeQuery("select * from LOGFILES"); 
                int i = 0;
                while(rs.next()){++i;}
                String server_name = combo_ser.getSelectedItem().toString();
                String filename = txt_logfile.getText().trim();
                String abspath = txt_path.getText().trim();
                String gname = combo_grp.getSelectedItem().toString();
           
                rs = s.executeQuery("select SID from SERVERS WHERE SERVER_NAME = \"" +server_name+"\" ;");
          
                rs.next();
                int sid = rs.getInt("SID");
                System.out.print("sid --------:"+sid);
                
                if((server_name.isEmpty() == false && filename.isEmpty() == false && abspath.isEmpty() == false && gname.isEmpty() == false))
                {
                    String q1 ="insert into LOGFILES values("+ ++i +",\""+filename+"\",\""+abspath+"\","+sid+");";
                    try{ 
                        s.execute(q1);
                        final JPanel panel = new JPanel();
                        JOptionPane.showMessageDialog(panel,filename+" "+"File added successfully.","Server",JOptionPane.INFORMATION_MESSAGE);
                    }
                    catch(Exception e){
                        final JPanel panel = new JPanel();
                        JOptionPane.showMessageDialog(panel,filename+" "+"File already exites","Server",JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                else{
                    final JPanel panel = new JPanel();
                    JOptionPane.showMessageDialog(panel,"Please check","Information",JOptionPane.WARNING_MESSAGE);
                }
                
            }
            catch(Exception e){
                System.out.print("error "+e);
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_grp;
    private javax.swing.JComboBox combo_ser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_logfile;
    private javax.swing.JTextField txt_path;
    // End of variables declaration//GEN-END:variables
}
